// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {git} from '../models';

export function AddRepository(arg1:string):Promise<config.Settings>;

export function AddWorktree(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function CheckoutRemoteBranch(arg1:string,arg2:string):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function DefaultWorktreePath(arg1:string,arg2:string):Promise<string>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DiscardHunk(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function Fetch(arg1:string):Promise<void>;

export function GetCommitFileDiff(arg1:string,arg2:string,arg3:string):Promise<git.FileDiff>;

export function GetFileDiff(arg1:string,arg2:string,arg3:boolean):Promise<git.FileDiff>;

export function GetSettings():Promise<config.Settings>;

export function GetStatus(arg1:string):Promise<Array<git.FileStatus>>;

export function ListBranchHeads(arg1:string):Promise<Array<git.BranchHead>>;

export function ListBranches(arg1:string):Promise<Array<git.BranchEntry>>;

export function ListCommitFiles(arg1:string,arg2:string):Promise<Array<git.CommitFileChange>>;

export function ListCommits(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<git.ListCommitsResult>;

export function ListWorktrees(arg1:string):Promise<Array<git.WorktreeEntry>>;

export function MergeBranch(arg1:string,arg2:string):Promise<void>;

export function OpenMergetool(arg1:string,arg2:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function Ping():Promise<string>;

export function Pull(arg1:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function RemoveRepository(arg1:string):Promise<config.Settings>;

export function ResetToCommit(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetActiveRepository(arg1:string):Promise<config.Settings>;

export function SquashMergeBranch(arg1:string,arg2:string):Promise<void>;

export function StageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function StageHunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string):Promise<void>;

export function UnstageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function UnstageHunk(arg1:string,arg2:string,arg3:number):Promise<void>;
