// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {git} from '../models';

export function AbortMerge(arg1:string):Promise<void>;

export function AbortRebase(arg1:string):Promise<void>;

export function AddRepository(arg1:string):Promise<config.Settings>;

export function AddWorktree(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function AmendCommit(arg1:string,arg2:string):Promise<void>;

export function ApplyStash(arg1:string,arg2:number):Promise<void>;

export function CheckoutRemoteBranch(arg1:string,arg2:string):Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<void>;

export function ContinueRebase(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function DefaultRemoteBaseRef(arg1:string):Promise<string>;

export function DefaultWorktreePath(arg1:string,arg2:string):Promise<string>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteRemoteBranches(arg1:string,arg2:Array<string>):Promise<void>;

export function DeleteUntracked(arg1:string,arg2:Array<string>):Promise<void>;

export function DiscardAllChanges(arg1:string):Promise<void>;

export function DiscardFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function DiscardHunk(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function DiscardLines(arg1:string,arg2:string,arg3:number,arg4:Array<number>,arg5:boolean):Promise<void>;

export function DropStash(arg1:string,arg2:number):Promise<void>;

export function Fetch(arg1:string):Promise<void>;

export function FetchPrune(arg1:string):Promise<Array<string>>;

export function GetAmendInfo(arg1:string):Promise<git.AmendInfo>;

export function GetCommitFileDiff(arg1:string,arg2:string,arg3:string):Promise<git.FileDiff>;

export function GetFileDiff(arg1:string,arg2:string,arg3:boolean):Promise<git.FileDiff>;

export function GetRangeFileDiff(arg1:string,arg2:string,arg3:string,arg4:string):Promise<git.FileDiff>;

export function GetRepoOperationState(arg1:string):Promise<git.RepoOperationState>;

export function GetSettings():Promise<config.Settings>;

export function GetStatus(arg1:string):Promise<Array<git.FileStatus>>;

export function GetWorktreeChangedCount(arg1:string):Promise<number>;

export function IsMerging(arg1:string):Promise<boolean>;

export function IsRebasing(arg1:string):Promise<boolean>;

export function ListBranchHeads(arg1:string):Promise<Array<git.BranchHead>>;

export function ListBranches(arg1:string):Promise<Array<git.BranchEntry>>;

export function ListCommitFiles(arg1:string,arg2:string):Promise<Array<git.CommitFileChange>>;

export function ListCommits(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string):Promise<git.ListCommitsResult>;

export function ListRangeFiles(arg1:string,arg2:string,arg3:string):Promise<Array<git.CommitFileChange>>;

export function ListRemoteMergeStatus(arg1:string,arg2:string,arg3:string):Promise<Array<git.RemoteMergeEntry>>;

export function ListStashes(arg1:string):Promise<Array<git.StashEntry>>;

export function ListWorktrees(arg1:string):Promise<Array<git.WorktreeEntry>>;

export function ListWorktreesMeta(arg1:string):Promise<Array<git.WorktreeEntry>>;

export function MergeBranch(arg1:string,arg2:string):Promise<void>;

export function OpenCommitDifftool(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenDifftool(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function OpenMergetool(arg1:string,arg2:string):Promise<void>;

export function OpenRangeDifftool(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function Ping():Promise<string>;

export function PopStash(arg1:string,arg2:number):Promise<void>;

export function Pull(arg1:string):Promise<void>;

export function PullRebase(arg1:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function PushSetUpstream(arg1:string,arg2:string):Promise<void>;

export function RebaseBranch(arg1:string,arg2:string):Promise<void>;

export function RemoveRepository(arg1:string):Promise<config.Settings>;

export function RemoveWorktree(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RenameBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetToCommit(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<config.Settings>;

export function SaveStash(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetActiveRepository(arg1:string):Promise<config.Settings>;

export function SetPushAfterCommit(arg1:string,arg2:boolean):Promise<config.Settings>;

export function ShowInExplorer(arg1:string):Promise<void>;

export function SquashMergeBranch(arg1:string,arg2:string):Promise<void>;

export function StageAll(arg1:string):Promise<void>;

export function StageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function StageHunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function StageLines(arg1:string,arg2:string,arg3:number,arg4:Array<number>):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string):Promise<void>;

export function UnstageAll(arg1:string):Promise<void>;

export function UnstageFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function UnstageHunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UnstageLines(arg1:string,arg2:string,arg3:number,arg4:Array<number>):Promise<void>;
