// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1) {
  return window['go']['app']['App']['AddRepository'](arg1);
}

export function AddWorktree(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddWorktree'](arg1, arg2, arg3, arg4);
}

export function CheckoutRemoteBranch(arg1, arg2) {
  return window['go']['app']['App']['CheckoutRemoteBranch'](arg1, arg2);
}

export function Commit(arg1, arg2) {
  return window['go']['app']['App']['Commit'](arg1, arg2);
}

export function CreateBranch(arg1, arg2) {
  return window['go']['app']['App']['CreateBranch'](arg1, arg2);
}

export function DefaultWorktreePath(arg1, arg2) {
  return window['go']['app']['App']['DefaultWorktreePath'](arg1, arg2);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function DiscardHunk(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DiscardHunk'](arg1, arg2, arg3, arg4);
}

export function Fetch(arg1) {
  return window['go']['app']['App']['Fetch'](arg1);
}

export function GetCommitFileDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetCommitFileDiff'](arg1, arg2, arg3);
}

export function GetFileDiff(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFileDiff'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStatus(arg1) {
  return window['go']['app']['App']['GetStatus'](arg1);
}

export function ListBranchHeads(arg1) {
  return window['go']['app']['App']['ListBranchHeads'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['app']['App']['ListBranches'](arg1);
}

export function ListCommitFiles(arg1, arg2) {
  return window['go']['app']['App']['ListCommitFiles'](arg1, arg2);
}

export function ListCommits(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListCommits'](arg1, arg2, arg3, arg4, arg5);
}

export function ListWorktrees(arg1) {
  return window['go']['app']['App']['ListWorktrees'](arg1);
}

export function MergeBranch(arg1, arg2) {
  return window['go']['app']['App']['MergeBranch'](arg1, arg2);
}

export function OpenMergetool(arg1, arg2) {
  return window['go']['app']['App']['OpenMergetool'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function Pull(arg1) {
  return window['go']['app']['App']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['app']['App']['Push'](arg1);
}

export function RemoveRepository(arg1) {
  return window['go']['app']['App']['RemoveRepository'](arg1);
}

export function ResetToCommit(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResetToCommit'](arg1, arg2, arg3);
}

export function SetActiveRepository(arg1) {
  return window['go']['app']['App']['SetActiveRepository'](arg1);
}

export function SquashMergeBranch(arg1, arg2) {
  return window['go']['app']['App']['SquashMergeBranch'](arg1, arg2);
}

export function StageFiles(arg1, arg2) {
  return window['go']['app']['App']['StageFiles'](arg1, arg2);
}

export function StageHunk(arg1, arg2, arg3) {
  return window['go']['app']['App']['StageHunk'](arg1, arg2, arg3);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['app']['App']['SwitchBranch'](arg1, arg2);
}

export function UnstageFiles(arg1, arg2) {
  return window['go']['app']['App']['UnstageFiles'](arg1, arg2);
}

export function UnstageHunk(arg1, arg2, arg3) {
  return window['go']['app']['App']['UnstageHunk'](arg1, arg2, arg3);
}
